name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  continuous-integration:
    if: >
      (github.event_name != 'pull_request' || github.event.pull_request.draft == false) &&
      !contains(github.event.head_commit.message || '', '[SKIP-CI]') &&
      !contains(github.event.pull_request.title || '', '[SKIP-CI]')
    strategy:
      matrix:
        os:
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - uses: actions/checkout@v1
      - name: Test
        run: swift test
